export const STRINGS = {
  app: {
    brand: 'mono',
  },
  onboarding: {
    headline: 'Spend Smarter\nSave More',
    cta: 'Get Started',
    signInPrompt: 'Already have an account?',
    signInLink: 'Log In',
  },
  common: {
    loading: 'Loading...',
    save: 'Save',
    pay: 'Pay',
    next: 'Next',
    cancel: 'Cancel',
    confirm: 'Confirm',
    done: 'Done',
    reset: 'Reset',
    success: 'Success',
    error: 'Error',
    today: 'Today',
    income: 'Income',
    expense: 'Expense',
    sampleAmount: '₹ 1800.00',
  },
  auth: {
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to sync your expenses',
    registerTitle: 'Create Account',
    registerSubtitle: 'Sign up to start tracking expenses across devices',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    fullNamePlaceholder: 'Full Name',
    loginButton: 'Log In',
    registerButton: 'Register',
    signUpPrompt: "Don't have an account?",
    signInPrompt: 'Already have an account?',
    signUpLink: 'Sign Up',
    signInLink: 'Log In',
    validationTitle: 'Validation Error',
    loginErrorTitle: 'Login Error',
    registrationErrorTitle: 'Registration Error',
    loginGenericError: 'Something went wrong',
    registrationGenericError: 'Could not register account.',
  },
  home: {
    quickActions: 'Quick actions',
    quickActionsSubtitle: 'Manage your money in one tap',
    recentTransactions: 'Recent transactions',
    recentTransactionsSubtitle: 'Your latest activity',
    seeAll: 'See all',
    addMoney: 'Add money',
    send: 'Send',
    payBill: 'Pay bill',
    dashboardReady: 'Your dashboard is up to date',
    dashboardEmpty: 'Start tracking your spending',
    dashboardReadySubtitle:
      'Your latest transactions are saved and synced with the cloud.',
    dashboardEmptySubtitle:
      'Add your first income or expense to see live totals.',
  },
  wallet: {
    title: 'Wallet',
    totalBalance: 'Total Balance',
    transactions: 'Transaction',
    upcomingBills: 'Upcoming Bills',
  },
  profile: {
    title: 'Profile',
    accountInfo: 'Account Info',
    personalProfile: 'Personal profile',
    messageCenter: 'message center',
    loginAndSecurity: 'login and security',
    dataAndPrivacy: 'Data and privacy',
    handle: '@rajesh_nani',
    accountTitle: 'Account Information',
    accountSubtitle: 'Keep your contact details current.',
    personalTitle: 'Personal Profile',
    personalSubtitle: 'Share a short bio and display name.',
    messageTitle: 'Message Center',
    messageSubtitle:
      'Messages, reminders, and account updates will show here.',
    messageUpdates: 'Recent Updates',
    messageEmptyTitle: 'No new messages',
    messageEmptySubtitle:
      'You’re all caught up. Notifications will appear here.',
    messageTip:
      'Tip: keep notifications enabled to receive account reminders and security alerts.',
    privacyTitle: 'Data and Privacy',
    privacySubtitle:
      'See how your data is stored, synced, and protected.',
    privacyEncryptionTitle: 'Encryption at rest',
    privacyEncryptionSubtitle: 'Your local records stay encrypted on device.',
    privacyCloudTitle: 'Cloud sync',
    privacyCloudSubtitle:
      'Only synced records are sent to your backend services.',
    privacyAccountTitle: 'Account data',
    privacyAccountSubtitle:
      'Profile and login details are used only for authentication.',
    privacyControlTitle: 'You control your data',
    privacyControlSubtitle:
      'You can clear local data from Security settings at any time.',
    namePlaceholder: 'Name',
    emailPlaceholder: 'Email',
    phonePlaceholder: 'Phone Number',
    bioPlaceholder: 'Bio',
    saveProfile: 'Save Profile',
    saveAccount: 'Save Account',
  },
  addTransaction: {
    addIncome: 'Add Income',
    addExpense: 'Add Expense',
    addIncomeTitle: 'Add Income',
    addExpenseTitle: 'Add Expense',
    category: 'Category',
    selectCategory: 'Select a category',
    loadingCategories: 'Loading categories...',
    customCategory: 'Custom category',
    openCamera: 'Open camera',
    uploadImage: 'Upload image',
    enterAmount: 'Enter the amount',
    selectDate: 'Select the date',
    chooseCategoryTitle: 'Choose a category',
    chooseCategoryMessage:
      'Select a category before saving this transaction.',
    invalidAmountTitle: 'Enter a valid amount',
    invalidAmountMessage: 'Amount must be greater than zero.',
    saving: 'Saving...',
    cameraHint: 'Capture a bill or receipt instantly.',
    galleryHint: 'Upload a receipt from your gallery.',
    categoryNamePlaceholder: 'Category name',
    categorySavedAs: 'This will be saved as an',
    defaultCategory: 'General',
    openCameraTitle: 'Open camera',
    uploadImageTitle: 'Upload image',
    resetTitle: 'Reset',
    chooseCategoryErrorTitle: 'Choose a category',
    chooseCategoryErrorMessage: 'Select a category before saving this transaction.',
    saveErrorTitle: 'Unable to save transaction',
    saveErrorMessage: 'Please try again.',
    categoryLoadError: 'Please try after some time.',
    customSheetTitle: 'Custom category',
    customCategoryLabel: 'Custom category',
    cameraActionHint: 'Capture a bill or receipt instantly.',
    galleryActionHint: 'Upload a receipt from your gallery.',
  },
  chat: {
    title: 'AI Assistant',
    emptyTitle: 'Ask me anything',
    emptySubtitle:
      'Ask about spending, monthly summaries, or transaction history.',
    thinking: 'AI is thinking...',
    fallbackError: 'Something went wrong. Check your server.',
    micPermissionTitle: 'Microphone Permission',
    micPermissionMessage:
      'This app needs microphone access to record your voice.',
    deniedMic: 'Microphone permission denied',
    transcribing: 'Transcribing...',
    recording: 'Recording in progress',
  },
  security: {
    title: 'Security',
    save: 'Save',
    fingerprint: 'Fingerprint Login',
    faceId: 'Face ID',
    appLock: 'App Lock',
    autoLock: 'Auto Lock',
    logout: 'Logout',
    fingerprintUnavailable: 'Finger print Login is not available on this device',
    faceIdUnavailable: 'Face ID Login is not available on this device',
    biometricUnavailable:
      'Biometric authentication is not available on this device',
    immediately: 'Immediately',
    thirtySeconds: '30 Seconds',
    oneMinute: '1 Minute',
  },
  statistics: {
    title: 'Statistics',
    subtitle: 'Spot patterns in your spending and income.',
    weekly: 'Week',
    monthly: 'Month',
    outflow: 'Outflow',
    inflow: 'Inflow',
    summaryTitle: 'Spending overview',
    summarySubtitle: 'Compare weekly and monthly trends.',
    outflowLabel: 'Outflow',
    inflowLabel: 'Inflow',
    chartHint:
      'Switch between outflow and inflow to compare your money flow.',
  },
  billDetails: {
    title: 'Bill Details',
    merchant: 'Youtube Premium',
    date: 'Feb 28, 2022',
    price: 'Price',
    fee: 'Fee',
    total: 'Total',
    paymentMethod: 'Select Payment method',
    debitCard: 'Debit Card',
    paypal: 'Paypal',
    payNow: 'Pay Now',
  },
  floating: {
    addExpenses: 'Add Expenses',
    addIncome: 'Add Income',
    chatWithAI: 'Chat with AI',
  },
  dashboard: {
    refresh: 'Refresh',
    wallet: 'Wallet',
    cardChange: 'Card change',
    exit: 'Exit',
  },
  alerts: {
    validationTitle: 'Validation Error',
    pleaseFillFields: 'Please fill in all fields.',
    enterBothAuth: 'Please enter both email and password.',
    weakPasswordTitle: 'Weak Password',
    passwordTooShort: 'Password must be at least 6 characters long.',
    incorrectPin: 'Incorrect PIN',
    pinLength: 'Enter a 4-digit PIN',
    pinMismatch: 'PINs do not match',
    pinCreated: 'PIN created successfully.',
    unableToSavePin: 'Unable to save PIN',
    pinCreatedTitle: 'Success',
    createPinTitle: 'Create your PIN',
    enterPinTitle: 'Enter your PIN',
    createPinButton: 'Create PIN',
    unlockButton: 'Unlock',
    categoryRequired: 'Select a category before saving this transaction.',
    invalidAmount: 'Amount must be greater than zero.',
    unableToSaveTransaction: 'Please try again.',
    transcriptionFailed: 'Transcription failed. Check your server.',
  },
  transaction: {
    emptySubtitle: 'Your saved activity will appear here.',
  },
} as const;
